apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: reloj
  namespace: "meetup-devops"
spec:
  replicas: 2
  template: 
    metadata:
      labels:
        app: reloj
    spec:
      containers:
      - name: reloj
        image: meetup/reloj:0.0.1
        ports:
        - containerPort: 3000
---

apiVersion: v1
kind: Service
metadata:
  name: reloj
  labels:
    name: reloj
  namespace: meetup-devops
spec:
  selector:
    name: reloj
  ports:
    - port: 3000
      targetPort: 3000
  type: LoadBalancer
