apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: reloj
  namespace: "meetup-devops"
spec:
  replicas: 1
  template: 
    metadata:
      labels:
        name: reloj
    spec:
      containers:
      - name: reloj
        image: meetup/reloj:0.0.2
        ports:
        - containerPort: 3000


+